#DATA
data_root: /path/to/tooth_3d
classes: 33
modality: CT


#MODEL
arch: medformer
in_chan: 1
base_chan: 32
conv_block: 'BasicBlock'

down_scale: [[1,2,2], [1,2,2], [2,2,2], [2,2,2]]
kernel_size: [[1,3,3], [1,3,3], [3,3,3], [3,3,3], [3,3,3]]
chan_num: [64, 128, 256, 320, 256, 128, 64, 32]
norm: in
act: relu
map_size: [3,3,3]
conv_num: [2,0,0,0, 0,0,2,2]
trans_num: [0,2,4,6, 4,2,0,0]
num_heads: [1,4,8,10, 8,4,1,1]
expansion: 4
fusion_depth: 2
fusion_dim: 320
fusion_heads: 10
attn_drop: 0
proj_drop: 0
proj_type: 'depthwise'


#TRAIN
epochs: 200
training_size: [64, 160, 160]
start_epoch: 0
num_workers: 2
aug_device: 'cpu'

aux_loss: True
aux_weight: [0.5, 0.5]

split_seed: 0
k_fold: 5

patch_index_enabled: False
patch_index_file: null
patch_index_cache_cases: 2

optimizer: adamw
base_lr: 0.0004
betas: [0.9, 0.999]
weight_decay: 0.05
weight: [0.2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
rlt: 1

scale: [0.2, 0.2, 0.2]
rotate: [20, 20, 20]
translate: [0, 0, 0]
affine_pad_size: [48, 48, 48]
gaussian_noise_std: 0.02

print_freq: 5
iter_per_epoch: 300


#VALIDATION
ema: True
ema_alpha: 0.99
val_freq: 10


#INFERENCE
sliding_window: True
window_size: [64, 160, 160]


# DDP
world_size: 1
proc_idx: 0
rank: 0
port: 10000
dist_url: 'tcp://localhost:10000'
dist_backend: "nccl"
multiprocessing_distributed: true
reproduce_seed: null

